[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
collaterals = "xcoL9qKXpLrXb67xNBzfsXboH8zsC9SorT9rES2viA3"
fees = "xfeewAjbVVJkjXUaxQxSmWgLNrixEFMJN3oNhNxQvCY"
peg_keeper = "xpeguefXy5MrgkbirCyuCCD5EfbUM5UfejdQduDcGz6"
team = "xtm3VMkqiNhP2rd74yZUzsXFZMyAJapmcP7HUSfwD4i"
vault = "xva8xAjCCadQpphx5wCXnoLf5rkZuYu85Xxt88V3XnK"
xive = "xiveHxXiqHUkFnX5DsmTsAbByTZS5bdGGpdZ9wpmNCR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
